library(readxl)
library(tidyverse)

# survey waves 12, 8, 4 

# download 2022 data

download.file("https://ca-barometer.org/assets/files/projects/cab-survey-wave-12-excel-kyrgyzstan-kyrgyzstan-2022-autumn.xlsx", "CAB_2022_KG.csv")
data_22_KG <- read_excel("CAB_2022_KG.csv")

download.file("https://ca-barometer.org/assets/files/projects/cab-survey-wave-12-excel-kazakhstan-kazakhstan-2022-autumn.xlsx", "CAB_2022_KZ.csv")
data_22_KZ <- read_excel("CAB_2022_KZ.csv")

download.file("https://ca-barometer.org/assets/files/projects/cab-survey-wave-12-excel-uzbekistan-uzbekistan-2022-autumn.xlsx", "CAB_2022_UZ.csv")
data_22_UZ <- read_excel("CAB_2022_UZ.csv")

download.file("https://ca-barometer.org/assets/files/projects/cab-survey-wave-12-excel-turkmenistan-turkmenistan-2022-autumn.xlsx", "CAB_2022_TM.csv")
data_22_TM <- read_excel("CAB_2022_TM.csv")

download.file("https://ca-barometer.org/assets/files/projects/cab-survey-wave-12-excel-tajikistan-tajikistan-2022-autumn.xlsx", "CAB_2022_TJ.csv")
data_22_TJ <- read_excel("CAB_2022_TJ.csv")

# download 2020 data

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-8-excel-kyrgyzstan-2020-autumn.xlsx", "CAB_2020_KG.csv")
data_20_KG <- read_excel("CAB_2020_KG.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-8-excel-kazakhstan-2020-autumn.xlsx", "CAB_2020_KZ.csv")
data_20_KZ <- read_excel("CAB_2020_KZ.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-8-excel-uzbekistan-2020-autumn.xlsx", "CAB_2020_UZ.csv")
data_20_UZ <- read_excel("CAB_2020_UZ.csv")

# no 2020 Turkmenistan data
# download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-8-excel-turkmenistan-2020-autumn.xlsx", "CAB_2020_TM.csv")
# data_20_TM <- read_excel("CAB_2020_TM.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-8-excel-tajikistan-2020-autumn.xlsx", "CAB_2020_TJ.csv")
data_20_TJ <- read_excel("CAB_2020_TJ.csv")

# download 2018 data

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-4-excel-kyrgyzstan-2018-autumn.xlsx", "CAB_2018_KG.csv")
data_18_KG <- read_excel("CAB_2018_KG.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-4-excel-kazakhstan-2018-autumn.xlsx", "CAB_2018_KZ.csv")
data_18_KZ <- read_excel("CAB_2018_KZ.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-4-excel-uzbekistan-2018-autumn.xlsx", "CAB_2018_UZ.csv")
data_18_UZ <- read_excel("CAB_2018_UZ.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-4-excel-turkmenistan-2018-autumn.xlsx", "CAB_2018_TM.csv")
data_18_TM <- read_excel("CAB_2018_TM.csv")

download.file("https://ca-barometer.org/assets/files/projects/central-asia-barometer-survey-wave-4-excel-tajikistan-2018-autumn.xlsx", "CAB_2018_TJ.csv")
data_18_TJ <- read_excel("CAB_2018_TJ.csv")

# merge data
# Country variable exists as MM4 in 2022, 2020, but labeled as 'Country'
# in 2018 data, so we introduce Country variable to match

data_22_KG <- mutate(data_22_KG, Country = 'Kyrgyzstan')
data_20_KG <- mutate(data_20_KG, Country = 'Kyrgyzstan')

# data_18_KG <- mutate(data_18_KG, Country = 'KG')

data_22_KZ <- mutate(data_22_KZ, Country = 'Kazakhstan')
data_20_KZ <- mutate(data_20_KZ, Country = 'Kazakhstan')

# data_18_KZ <- mutate(data_18_KZ, Country = 'KZ')

data_22_UZ <- mutate(data_22_UZ, Country = 'Uzbekistan')
data_20_UZ <- mutate(data_20_UZ, Country = 'Uzbekistan')

# data_18_UZ <- mutate(data_18_UZ, Country = 'UZ')

data_22_TM <- mutate(data_22_TM, Country = 'Turkmenistan')

# data_20_TM <- mutate(data_20_TM, Country = 'TM')
# data_18_TM <- mutate(data_18_TM, Country = 'TM')

data_22_TJ <- mutate(data_22_TJ, Country = 'Tajikistan')
data_20_TJ <- mutate(data_20_TJ, Country = 'Tajikistan')

# data_18_TJ <- mutate(data_18_TJ, Country = 'TJ')

# rbind
# must careful for same variables, so we must clean data first

data_2022 <- rbind(data_22_KZ, data_22_KG, data_22_TJ, data_22_TM, data_22_UZ)
#error

setdiff(names(data_22_KG),names(data_22_KZ))
setdiff(names(data_22_KG),names(data_22_UZ))
setdiff(names(data_22_KZ),names(data_22_UZ))

my_test_join <- full_join(data_22_KG, data_22_KZ)

data_22_KG$MM8

data_22_KZ$MM8

data_20_KG$MM8

data_20_KZ$MM8

data_18_KG$MM6

data_18_KZ$MM6


# we don't care about this level of detail, so let's introduce a similar "Year" variable into the data
# this will also overwrite the variable type, but we can double check it

data_22_KG$MM8 <- 2022
data_22_KZ$MM8 <- 2022
data_22_UZ$MM8 <- 2022

data_20_KG$MM8 <- 2020
data_20_KZ$MM8 <- 2020
data_20_UZ$MM8 <- 2020

class(data_22_KG$MM8)
mode(data_22_KG$MM8)

class(data_22_KZ$MM8)
mode(data_22_KZ$MM8)

# date is MM6 in 2018, but labeled 'Year' - gotta watch those codebooks

data_18_KG$Year

data_18_KZ$Year

class(data_18_KG$Year)
mode(data_18_KG$Year)

# no need to overwrite

# try again

my_test_join <- full_join(data_22_KG, data_22_KZ)

# works now

# set them all to 'Year'

```{r renaming}

data_22_KG <- data_22_KG |> rename('Year'='MM8')
data_22_KZ <- data_22_KZ |> rename('Year'='MM8')
data_22_UZ <- data_22_UZ |> rename('Year'='MM8')

```

# we could merge and work with the entire group of datasets, merging the 9 files together, 3 years x 3 countries
# we'd then have access to all the variables

# let's just select our variables of interest first though, to make the output more comprehensible and browseable
# this way we can also pre-clean and check variables for compatibility

# look at the smaller 2018 survey first to try to isolate things that are comparable across all years

# 2018
what currency you keeep your dough in?
  DD9d
(not used 

% income from remittances
DD9a
(not used in 2020? 2022 has it )

DD1 Gender DD2 Age DD3 Marital Stauts DD4 Edicatopm DD6a emp status

E1a. China
E1b. Russia
E1c. United States

favorability of the coutnries above

A2a. Television
A2b. Newspaper
A2c. Radio

trust these source
(not used after )
A1a main source of newsy



D1 right or wrong direction of our country

dd11 language at home (2022 too)

2020
dd9 is langueage at home 

B4a coutnry financial sit bet or wros (was B2 in 2018)
b4b  (was B6a in 2018)
familiy financial sit bet or worse

a1a main source of news

# so with this info, let's create a combi file

mydata2022 <- full_join(data_22_KG, data_22_KZ)
mydata2022 <- full_join(mydata2022, data_22_UZ)
mydata2020 <- full_join(data_20_KG, data_20_KZ)
mydata2020 <- full_join(mydata2020, data_20_UZ)
mydata2018 <- full_join(data_18_KG, data_18_KZ)
mydata2018 <- full_join(mydata2018, data_18_UZ)

# a problem with $$HHLandlines in last line
data_18_UZ$HHLandlines <- as.character(data_18_UZ$HHLandlines)
mydata2018 <- full_join(mydata2018, data_18_UZ)

# we could merge them again, but that would be messy and get screwed up with changing variable names

# again we'll have the naming issue

My final list of selected variables
  DD1 Gender
  DD2 Age
  DD3 Marital (Status)
  DD4 Education
  DD6a Employment
  
  D1 Direction (Right or Wrong)
  
  E1a China_Favor
  E1b Russia_Favor
  E1c USA_Favor
  
  DD9a Remit (Remittances in 2018, 2022)
  
  A1a Main_News (Source)
  
  DD11 Language (at Home) DD9 in 2020
  
  B4a Country_Fin_Sit  (B2 in 2018)
  B4b Family_Fin_Sit   (B5a in 2018)
  
  plus keep Country, Year
  
rename them with

names(mydata2018)
names(mydata2020)
names(mydata2022)

# review those again

mydata2022 <- mydata2022 |> rename('Sex'='DD1', 'Age'='DD2', 'Marital'='DD3',
                                   'Education'='DD4', 'Employment'='DD6a', 
                                   'Direction'='D1', 'China_Favor'='E1a',
                                   'Russia_Favor'='E1b','USA_Favor'='E1c',
                                   'Main_News'='A1a', 'Remit'='DD9a',
                                   'Language'='DD11','Country_Fin_Sit'='B4a',
                                   'Family_Fin_Sit'='B4b')

mydata2022_select <- mydata2022 |> select('Sex', 'Age', 'Marital', 'Education', 
                                          'Employment', 'Direction', 'China_Favor',
                                          'Russia_Favor','USA_Favor', 'Main_News', 
                                          'Remit', 'Language','Country_Fin_Sit',
                                          'Family_Fin_Sit', 'Country', 'Year')

# note we rename Year here from MM8

mydata2020 <- mydata2020 |> rename('Sex'='DD1', 'Age'='DD2', 'Marital'='DD3',
                                   'Education'='DD4', 'Employment'='DD6a', 
                                   'Direction'='D1', 'China_Favor'='E1a',
                                   'Russia_Favor'='E1b','USA_Favor'='E1c',
                                   'Main_News'='A1a', 'Language'='DD9',
                                   'Country_Fin_Sit'='B4a', 'Family_Fin_Sit'='B4b',
                                   'Year'='MM8')

mydata2020_select <- mydata2020 |> select('Sex', 'Age', 'Marital', 'Education', 
                                          'Employment', 'Direction', 'China_Favor',
                                          'Russia_Favor','USA_Favor', 'Main_News', 
                                          'Language','Country_Fin_Sit',
                                          'Family_Fin_Sit', 'Country', 'Year')
# need to add a blank 'Remit' variable here

mydata2020_select <- mydata2020_select |> mutate(Remit=NA)

# and 2018 data already uses the names, but formatted differently
# codebook is not satisfactory, does not describe these labels, have to judege by answers in some cases
# note the 'LangExtra' to avoid repeating a name

mydata2018 <- mydata2018 |> rename('Sex'='Gender', 'Marital'='MarriageStat2',
                                   'Education'='EducLevel_M', 'Employment'='Work', 
                                   'Direction'='RiteRong_M', 'China_Favor'='OpinionChina',
                                   'Russia_Favor'='OpinionRussia','USA_Favor'='OpinionUSA',
                                   'Main_News'='MainNews_M', 'Language'='Homelang','LangExtra'='Language',
                                   'Country_Fin_Sit'='TodayEcSit_M', 'Family_Fin_Sit'='Lastyear_M',
                                   'Remit'='IncomeOut')

mydata2018_select <- mydata2018 |> select('Sex', 'Age', 'Marital', 'Education', 
                                          'Employment', 'Direction', 'China_Favor',
                                          'Russia_Favor','USA_Favor', 'Main_News', 
                                          'Language','Country_Fin_Sit', 'Remit',
                                          'Family_Fin_Sit', 'Country', 'Year')

# now we'll do an old school rbind

my_final_data <- rbind(mydata2018_select, mydata2020_select, mydata2022_select)
str(my_final_data)
summary(my_final_data)

attach(my_final_data)

# tables

table(Sex)

table(Age)

table(Marital)

table(Education)

table(Employment)

table(Direction)

table(China_Favor)

table(Sex)

table(Russia_Favor)

table(USA_Favor)

table(Main_News)

table(Country_Fin_Sit)

table(Remit)
#fix dat
my_final_data$Remit<-as.numeric(Remit)
attach(my_final_data)

table(Remit)


table(Family_Fin_Sit)

table(Country)

table(Year)

#should we clean the 2019 ? perhaps - let's leave it and see how dirty the data gets

# Remit is at least one variable good for scatterplot - most are not

plot(Remit~Year)

# not very interesting is it?
abline(lm(Remit~Year), col="red")

plot(Remit~Age)

library(lattice)

xyplot(Remit~Age, groups=Country, auto.key=list(space="right"))
xyplot(Remit~Age | Country , groups=Language, auto.key=list(space="right"))
xyplot(Remit~Age | Country , groups=Marital, auto.key=list(space="right"))

plot(Remit~Language)

plot(price~carat, col="steelblue", pch=3, main="Diamond Data", xlab="weight of diamond in carats", 
     ylab="price of diamond in dollars", xlim=c(0,3))

# lattice
xyplot(price~carat)
xyplot(price~carat | cut)
xyplot(price~carat, groups=cut)
xyplot(price~carat | cut + clarity)
xyplot(price~carat | cut , groups=clarity, auto.key=list(space="right"))

# grid
# aesthetics

ggplot(my_final_data, aes(y=Remit, x=Age))  + facet_grid(.~Country) + geom_point(aes(color=Sex))
ggplot(my_final_data, aes(y=Remit, x=Age))  + facet_grid(Country~.) + geom_point(aes(color=Marital))
#labeling
ggplot(my_final_data, aes(y=Remit, x=Age))  + facet_grid(Country~.) + geom_point(aes(color=Marital))+
labs(x="age", y="% remittances", title="Remittance as percentage of income")

# keep refining
ggplot(my_final_data, aes(x=Remit, y=Age))  + facet_grid(.~Country) + geom_point(aes(color=Marital))+
  labs(x="age", y="% remittances", title="Remittance as percentage of income")

# point size

ggplot(my_final_data, aes(x=Remit, y=Age))  + facet_grid(.~Country) + geom_point(aes(color=Marital), size=3)+
  labs(x="age", y="% remittances", title="Remittance as percentage of income")

# note we can do similar with font sizes and other elements

xyplot(price~carat, col="steelblue", pch=3, main="Diamond Data", xlab="weight of diamond in carats", 
       ylab="price of diamond in dollars", xlim=c(0,3), scales=list(tick.number=10))

# most of our data is split into categories, so things like bar charts will be better 

# barchart

# dull right?
ggplot(my_final_data, aes(x=Sex) + geom_bar(position="stack") 

ggplot(my_final_data, aes(x=Sex, fill=Country)) + geom_bar(position="stack") 

ggplot(my_final_data, aes(x=Sex, fill=Country)) + geom_bar(position="stack") + scale_fill_manual(values = country_colors)

ggplot(my_final_data, aes(x=Sex, fill=Country)) + geom_bar(position="stack") + scale_fill_brewer(palette = "Accent")

library(paletteer)
ggplot(my_final_data, aes(x=Sex, fill=Country)) + geom_bar(position="stack") +scale_fill_paletteer_d("nationalparkcolors::Hawaii")
ggplot(my_final_data, aes(x=Sex, fill=Country)) + geom_bar(position="stack") +scale_fill_paletteer_d("IslamicArt::samarqand2")

try also IslamicArt::samarqand
nbapalettes::lakers
MoMAColors::OKeeffe

# look at more interesting stuff

# color picker
https://r-charts.com/colors/

  paletteos
  https://r-graph-gallery.com/38-rcolorbrewers-palettes.html
  https://r-graph-gallery.com/ggplot2-color.html
country_colors <- c("turquoise1","firebrick1","seagreen3")
       
ggplot(my_final_data, aes(China_Favor, fill=Country))+ geom_bar(position="stack") + scale_fill_manual(values = country_colors)
ggplot(my_final_data, aes(China_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors)
ggplot(my_final_data, aes(Russia_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors)
ggplot(my_final_data, aes(USA_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors)

China <- ggplot(my_final_data, aes(China_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors) + coord_flip()
Russia <- ggplot(my_final_data, aes(Russia_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors) + coord_flip()
USA <- ggplot(my_final_data, aes(USA_Favor, fill=Country))+ geom_bar(position="dodge") + scale_fill_manual(values = country_colors) + coord_flip()
# pile them together
library(gridExtra)
grid.arrange(China,Russia,USA, ncol=1, nrow=3)

ggplot(diamonds, aes(clarity)) + facet_grid(.~Sex) + geom_bar(position="dodge")+
scale_fill_manual(values = country_colors)

paletteer even more extensive

https://r-graph-gallery.com/package/paletteer.html
https://r-graph-gallery.com/color-palette-finder.html

# save graph as R object
mygraph <- ggplot(diamonds, aes(x=carat,y=price)) + xlim(0,3) + geom_point(colour="steelblue", pch=3) + 
  labs(x="weight of diamond in carats", y="price of diamond in dollars", title="Diamond Data") 

# export to PDF (or JPEG, PNG)
pdf(file="output.pdf")
ggplot(diamonds, aes(clarity)) + facet_grid(.~cut) + geom_bar(position="dodge")
ggplot(diamonds, aes(x=carat,y=price)) + xlim(0,3) + geom_point(colour="steelblue", pch=3) + 
  labs(x="weight of diamond in carats", y="price of diamond in dollars", title="Diamond Data")
dev.off()

jpeg(file="output.jpg", width = 800, height = 600, quality=100)
ggplot(diamonds, aes(depth))+geom_histogram(aes(fill = after_stat(count)))
dev.off()

# histogram
ggplot(my_final_data, aes(Age))+geom_histogram(aes(fill = after_stat(count)))+facet_grid(Country~.)
ggplot(diamonds, aes(depth))+geom_histogram(aes(fill = after_stat(count)))

# theme tweaks
ggplot(my_final_data, aes(Age)) +facet_grid(Country~.) + geom_bar(position="dodge", fill="olivedrab")+theme(panel.background = element_rect(fill='lightsteelblue1', colour='darkblue'))
ggplot(diamonds, aes(clarity)) +facet_grid(.~cut) + geom_bar(position="dodge")+theme(panel.background = element_rect(fill='white', colour='black'))
ggplot(diamonds, aes(x=clarity, fill=clarity)) +facet_grid(.~cut) + geom_bar(position="dodge")+ scale_fill_brewer(palette="Reds")


ggplot(my_final_data, aes(Employment_recode, fill=as.factor(Marital_recode))) +facet_grid(Country~.) + geom_bar(position="dodge") + theme(panel.background = element_rect(fill='beige', colour='darkblue'))
ggplot(my_final_data, aes(Employment_recode, fill=as.factor(Marital_recode))) +facet_grid(Country~.) + geom_bar(position="dodge") + theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Work status", y="Count", title="Employment by Marital Status") + coord_flip()

ggplot(my_final_data, aes(Employment_recode2, fill=as.factor(Marital_recode))) +facet_grid(Country~.) + geom_bar(position="dodge") + theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Work status", y="Count", title="Employment by Marital Status") + coord_flip()

ggplot(my_final_data, aes(Employment_recode2, fill=Country)) +facet_grid(Marital_recode~.) + geom_bar(position="dodge") + scale_fill_manual(values=country_colors)+theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Work status", y="Count", title="Employment by Marital Status") 

# Direction by factors

ggplot(my_final_data, aes(Direction, fill=Country)) + geom_bar(position="dodge") + scale_fill_manual(values=country_colors)+theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Respone", y="Count", title="Going in Right or Wrong Direction?") 

ggplot(my_final_data, aes(Direction, fill=Country)) + facet_grid(Year~.) + geom_bar(position="dodge") + scale_fill_manual(values=country_colors)+theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Respone", y="Count", title="Going in Right or Wrong Direction?") 

ggplot(my_final_data, aes(Direction_recode, fill=Country)) + facet_grid(Family_Fin_Sit_recode~.) + geom_bar(position="dodge") + scale_fill_manual(values=country_colors)+theme(panel.background = element_rect(fill='beige', colour='darkblue')) + 
  labs(x="Respone", y="Count", title="Going in Right or Wrong Direction vs. Family situation?") 

# using the power
mydata <- ggplot(diamonds, aes(clarity)) +facet_grid(.~cut) 
mytheme <- theme(panel.background = element_rect(fill='lightblue', colour='darkgrey'))
mychart <- geom_bar(position="dodge", fill="thistle", color="black")

mydata+mytheme+mychart

# regression
ggplot(diamonds, aes(x=carat, y=price)) + geom_point() + geom_smooth(method=lm)
ggplot(diamonds, aes(x=carat, y=price)) + geom_point() + stat_smooth()
ggplot(mtcars, aes(x=mpg, y=disp)) + geom_point() + stat_smooth()
# we can also plot customized confidence interval bands, but this requires computing them separately [see ggplot2 help]

# box plot
ggplot(diamonds, aes(x=color, y=price)) + geom_boxplot()
ggplot(diamonds, aes(x=color, y=price)) + geom_boxplot() + coord_flip()

# getting fancy
# first with scales
ggplot(diamonds, aes(x=carat, y=price)) + geom_point() + geom_smooth()
ggplot(diamonds, aes(x=carat, y=price)) + geom_point() + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")

# then with color
ggplot(diamonds, aes(x=carat, y=price, color="purple")) + geom_point() + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")
ggplot(diamonds, aes(x=carat, y=price)) + geom_point(color="purple") + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")
ggplot(diamonds, aes(x=carat, y=price)) + geom_point() + geom_smooth(color="purple") + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")
ggplot(diamonds, aes(x=carat, y=price)) + geom_point(aes(color=cut)) + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")
ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point() + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")
ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point(color="purple") + geom_smooth() + scale_y_continuous(trans="log") + scale_x_continuous(trans="log")

# then with ggthemes (see also ggsci, ggthemr)
lastplot <- ggplot(my_final_data, aes(x=Remit,y=Age))  + geom_point(aes(color=Country)) + stat_smooth() + 
  labs(x="Remittance %", y="Age", title="Age vs Remittance") 


> table(Marital, Employment)

> table(Marital, Education)

> table(Education, Employment)

# recode
my_final_data$Marital_recode <- replace_values(
  Marital,
  c("Don't Know (vol.)", "Refused (vol.)") ~ NA
)

my_final_data$Employment_recode <- replace_values(
  Employment,
  c("Don't Know (vol.)", "Refused (vol.)") ~ NA
)

my_final_data$Employment_recode2 <- replace_values(
  Employment,
  c("Working part-time", "Working full-time") ~ "Working",
  c("Unemployed and not actively seeking employment", "Unemployed and actively seeking employment") ~ "Unemployed",
  c("A housewife / househusband","A housewife") ~ "Housewife",
  c("Don't Know (vol.)", "Refused (vol.)") ~ NA
)

my_final_data$Direction_recode <- replace_values(
  Direction,
  c("Don't Know (vol.)", "Refused (vol.)", "Not asked") ~ NA
)

my_final_data$Family_Fin_Sit_recode <- replace_values(
  Family_Fin_Sit,
  c("Much better", "Much Better", "Become Better", "Somewhat better", "Somewhat Better") ~ "Better",
  c("About the same", "Stayed the Same") ~ "Same",
  c("Become Worse","Much Worse", "Much worse", "Somewhat Worse", "Somewhat worse") ~ "Worse",
  c("Don't Know (vol.)", "Refused (vol.)") ~ NA
)

attach(my_final_data)

table(Marital_recode,Employment_recode)
library(ggthemes)

lastplot + theme_bw()
lastplot + theme_dark()
lastplot + theme_economist()
lastplot + theme_fivethirtyeight()
lastplot + theme_tufte()
lastplot + theme_wsj()

# then with Rcolorbrewer
lastplot + theme_economist() + scale_color_brewer(palette = "Set3")
lastplot + theme_tufte() + scale_color_brewer(palette = "Dark2")
# lastdensity <-ggplot(diamonds, aes(x=carat, fill=clarity, color=clarity)) + geom_density(alpha=0.3, aes(y=..scaled..)) 
# lastdensity + theme_cowplot() + scale_fill_brewer(palette = "Dark2") + scale_color_brewer(palette = "Dark2")
# lastdensity + theme_tufte() + scale_fill_brewer(palette = "Set3") + scale_color_brewer(palette = "Set3")

library(ggiraph)
library(tidyverse)

myplot <- ggplot(
  data = my_final_data,
  mapping = aes(
    x = Remit, y = Age,
    # here we add interactive aesthetics
    tooltip = paste(Country,Marital)
  )
) +
  geom_point_interactive(
    size = 1, hover_nearest = TRUE
  )

interactive_plot <- girafe(ggobj = myplot)
htmltools::save_html(interactive_plot, "/home/ryan/R/ggiraph-2.html")

graphics

scatterplot

then grid it

then dress it

# a lot of detail, branches for each country though
# we are going to stick with the commonalities

# regress it

# plot the trends

# compute percentages
my_final_data$Direction_recode <- as.factor(Direction_recode)
attach(my_final_data)
mean(as.numeric(Direction_recode), na.rm=TRUE)

lm(data=my_final_data, Remit ~ .)
lm(data=my_final_data, Remit ~ Year)

levels(my_final_data$Direction_recode)

# forcats

fct_count(Direction_recode, sort = FALSE, prop = TRUE, na.rm=TRUE)

mytable <- fct_count(Direction_recode, sort = FALSE, prop = FALSE)

Direction_percent <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

fct_match(Direction_recode, "Right direction")

Now do a matrix of these 

Uz18<- my_final_data |> filter(Country=="Uzbekistan" & Year==2018)
Uz20<- my_final_data |> filter(Country=="Uzbekistan" & Year==2020)
Uz22<- my_final_data |> filter(Country=="Uzbekistan" & Year==2022)

Kz18<- my_final_data |> filter(Country=="Kazakhstan" & Year==2018)
Kz20<- my_final_data |> filter(Country=="Kazakhstan" & Year==2020)
Kz22<- my_final_data |> filter(Country=="Kazakhstan" & Year==2022)

Kg18<- my_final_data |> filter(Country=="Kyrgyzstan" & Year==2018)
Kg20<- my_final_data |> filter(Country=="Kyrgyzstan" & Year==2020)
Kg22<- my_final_data |> filter(Country=="Kyrgyzstan" & Year==2022)

# setup our matrix

Direction_pct_matrix <- data.frame(matrix(0,3,3))
rownames(Direction_pct_matrix) = c("Kazakhstan", "Kyrgyzstan", "Uzbekistan")
colnames(Direction_pct_matrix) = c("2018", "2020", "2022")



mytable <- fct_count(Kz18$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[1,1] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Kz20$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[1,2] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Kz22$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[1,3] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Kg18$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[2,1] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Kg20$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[2,2] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Kg22$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[2,3] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Uz18$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[3,1] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

mytable <- fct_count(Uz20$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[3,2] <- mytable[1,2]/(mytable[1,2]+mytable[2,2])

# this was the not asked question, so leave it alone
mytable <- fct_count(Uz22$Direction_recode, sort = FALSE, prop = FALSE)
Direction_pct_matrix[3,3] <- NA

Direction_pct_matrix <- cbind(Direction_pct_matrix, Country=c("Kazakhstan", "Kyrgyzstan", "Uzbekistan"))
Direction_long <- pivot_longer(Direction_pct_matrix, !Country, names_to="Year", values_to = "Value")
Direction_long$Year <- as.numeric(Direction_long$Year)
ggplot(Direction_long, aes(x=Year, y=Value, color=Country)) +
  geom_line()

#stepwise
